name: Validate

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-validate"
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: true
      matrix:
        node-version: [22.x]
        os: [ubuntu-24.04]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Saxon, ant
        run: |
          sudo apt-get update && sudo apt-get install openjdk-11-jre-headless ant -y --no-install-recommends
          ./src/scripts/shellscripts/dl_saxon.sh
      - name: Install Ant-Contrib
        run: |
          wget https://repo1.maven.org/maven2/ant-contrib/ant-contrib/1.0b3/ant-contrib-1.0b3.jar
          mv ant-contrib-1.0b3.jar /usr/share/ant/lib
      - name: Fetch Edition Data
        run: |
          ./src/scripts/shellscripts/fetch_data.sh
      - name: Build the site
        run: |
          ant -f ./src/scripts/ant/build.xml
      # Necessary because `actions/setup-node` does not yet support `corepack`.
      # @see https://github.com/actions/setup-node/issues/531
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Cache astro build artefacts
        uses: actions/cache@v4
        with:
          path: node_modules/.astro/
          key: ${{ runner.os }}-astro-${{ matrix.node-version }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-astro-${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint:check

      - name: Typecheck
        run: pnpm run types:check

      - name: Test
        run: pnpm run test

      - name: Get playwright version
        run: |
          PLAYWRIGHT_VERSION=$(pnpm ls @playwright/test --json | jq --raw-output '.[0].devDependencies["@playwright/test"].version')
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache playwright browsers
        uses: actions/cache@v4
        id: cache-playwright-browsers
        with:
          path: "~/.cache/ms-playwright"
          key: "${{ matrix.os }}-playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}"

      - name: Install playwright browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps
      - name: Install playwright browsers (operating system dependencies)
        if: steps.cache-playwright-browsers.outputs.cache-hit == 'true'
        run: pnpm exec playwright install-deps

      - name: Build app
        run: pnpm run build
        env:
          PUBLIC_APP_BASE_URL: "http://localhost:3000"
          PUBLIC_REDMINE_ID: "${{ vars.SERVICE_ID }}"
          PUBLIC_TYPESENSE_HOST: "${{ vars.PUBLIC_TYPESENSE_HOST }}"
          PUBLIC_TYPESENSE_PORT: "${{ vars.PUBLIC_TYPESENSE_PORT }}"
          PUBLIC_TYPESENSE_PROTOCOL: "${{ vars.PUBLIC_TYPESENSE_PROTOCOL }}"
          PUBLIC_TYPESENSE_COLLECTION_NAME: "${{ vars.PUBLIC_TYPESENSE_COLLECTION_NAME }}"
          PUBLIC_TYPESENSE_SEARCH_API_KEY: "${{ vars.PUBLIC_TYPESENSE_SEARCH_API_KEY }}"

      - name: Run e2e tests
        run: pnpm run test:e2e
        env:
          PUBLIC_APP_BASE_URL: "http://localhost:3000"

      - uses: actions/upload-artifact@v5
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  build-deploy:
    if: ${{ github.event_name == 'push' }}
    needs: [validate]
    uses: ./.github/workflows/build-deploy.yml
    secrets: inherit
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#access-and-permissions
    permissions:
      contents: read
      packages: write
